### PR TITLE
Upgrade phpunit to version 9 and update minimum php version to 7.3

### PR DESCRIPTION
**Pull request by alkaupp**
Hi Emily!

I failed running the tests with PHP8, so I added support for it. This required me to update phpunit to the latest major version, which in turn forced a minimum PHP version to be bumped to 7.3.

### CODE REVIEW

**Comment by alkaupp** [comment]
I added three more changes while I was test running this for the first time.

1. Session object is treated like a common array, so it fails when running the test
2. LocationService.isWithinDeliveryRange() was protected, and failed when running the test
3. Update the syntax of the test code

I tried the Java version too. Now uncommenting the test and running it for the first time produces `UnsupportedOperationException: missing from this exercise - shouldn't be called from a unit test` like the Java version. My assumption is that this is the intended behaviour when running this for the first time. What do you think? :)

**Comment by alkaupp** [comment]
Two more updates seemed necessary too...

When calling $shopping->switchStore(null), we got two errors. One in DeliveryInformation.setPickupLocation() and another one in Session.put().

I fixed those by making the arguments nullable.

**Comment by alkaupp** [comment]
I tried running the test on a fresh clone with PHP 7.4 this morning. Works as expected with PHP7 and PHP8 now. :+1:

**Comment by alkaupp** [comment]
:|

**Comment by codecop** [comment]
Minimal changes to the code, looks good. Thank you

**Pull request closed without merging**
